services:
  - type: web 
    name: identity-reconcilation-backend
    runtime: docker
    rootDir: server
    healthCheckPath: /
    envVars:
      - key: POSTGRES_DB
        envVarGroups: identity-reconciliation
      - key: POSTGRES_USER
        envVarGroups: identity-reconciliation
      - key: POSTGRES_PASSWORD
        envVarGroups: identity-reconciliation
      - key: POSTGRES_HOST
        envVarGroups: identity-reconciliation
      - key: POSTGRES_PORT
        envVarGroups: identity-reconciliation
      - key: PYTHONUNBUFFERED
        envVarGroups: identity-reconciliation
    
  - type: web
    name: postgres
    runtime: docker
    rootDir: database
    healthCheckPath: /
    envVars:
      - key: POSTGRES_DB
        envVarGroups: identity-reconciliation
      - key: POSTGRES_USER
        envVarGroups: identity-reconciliation
      - key: POSTGRES_PASSWORD
        envVarGroups: identity-reconciliation
      - key: PYTHONUNBUFFERED
        envVarGroups: identity-reconciliation

envVarGroups:
- name: identity-reconciliation
  envVars:
    - key: POSTGRES_DB
      generateValue: true
    - key: POSTGRES_USER
      generateValue: true
    - key: POSTGRES_PASSWORD
      generateValue: true
    - key: POSTGRES_HOST
      generateValue: true
    - key: POSTGRES_PORT
      generateValue: true
    - key: PYTHONUNBUFFERED
      generateValue: true
