version: '2'
services:
  identity-reconcilation-backend:
    build: ../server/
    command: python3 app.py 
    volumes:
      - ../server/:/usr/src/app/
    ports:
      - "5002:5002"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - HOST_IP
      - POSTGRES_PORT
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    build: ../database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d customer_data'"]
      interval: 10s
      timeout: 5s
      retries: 3
