version: '2'
services:
  web:
    build: ../server/
    command: python3 app.py 
    volumes:
      - ../server/:/usr/src/app/
    ports:
      - "5002:5002"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: customer_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    build: ../database
    ports:
      - "5432:5432"
