CREATE TABLE Contact (
    ID INT NOT NULL,
    PHONE_NUMBER VARCHAR(10),
    EMAIL VARCHAR(255),
    LINKED_ID INT,
    link_preference VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,
    PRIMARY KEY (ID)
)
