CREATE TABLE Contact (
    ID INT NOT NULL,
    PHONE_NUMBER VARCHAR(10),
    EMAIL VARCHAR(255),
    LINKEDID INT,
    LINK_PREFENCE VARCHAR(20) NOT NULL,
    CREATEDAT TIMESTAMP NOT NULL,
    UPDATEDAT TIMESTAMP NOT NULL,
    DELETEDAT TIMESTAMP,
    PRIMARY KEY (ID)
)
