name: test_run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
  POSTGRES_USER: ${{secrets.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
  POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
  POSTGRES_DB: ${{secrets.POSTGRES_DB}}
  PYTHONUNBUFFERED: ${{secrets.PYTHONUNBUFFERED}}

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./test/requirements.txt
      - name: Run Server for testing 
        run: |
          docker volume create ir_psql
          docker compose -f conf/docker-compose.yml up -d
      - name: Test with pytest
        run: |
          pytest test --self-contained-html --html=test/artifact/file.html 
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: test_report
          path: test/artifact/file.html
